start_year: {startyear}
end_year: {endyear}
start_month: 1
end_month: 12
frequency: "M"
skipdates:
input_dir: "/work/scratch-pw5/mattjbr/input/gear-hrly"
filename: "CEH-GEAR-1hr-v2_{start_date}.nc"
varnames:
  - "rainfall_amount"
  - "stat_disag"
  - "min_dist"
date_format: "%Y%m"
target_root: "/work/scratch-pw5/mattjbr/output"
store_name: "gearhrly_10km_chunks_{startyear}.zarr"
concatdim: "time"
concatvar: "time"
target_chunks: 
  time: 8784
  y: 10
  x: 10 
num_workers: 1
prune: 0 # no. of files to process, set to 0 to use all
overwrites: "off"
var_overwrites:
overwrite_source:
