start_year: 1980
end_year: 2080
start_month: 12
end_month: 11
input_dir: "/home/users/mattjbr/fdri/data/chess-scape/rcp85"
filename: "{ensmem}/daily/{varname}/chess-scape_rcp85_{ensmem}_{varname}_uk_1km_daily_{start_date}-{end_date}.nc"
varnames:
  - tas
  - tasmax
  - tasmin
  - rsds
  - rlds
  - huss
  - hurs
  - sfcWind
  - psurf
  - pr
  - dtr
ensmems:
  - "01"
  - "04"
  - "06"
  - "15"
date_format: "%Y%m%d" # use python datestring formatting codes https://docs.python.org/3/library/datetime.html#format-codes
target_root: "/work/scratch-nopw2/mattjbr"
store_name: "chess-scape_rcp85_01_yearly_100km_chunks.zarr"
target_chunks: 
  time: 360
  y: 100 
  x: 100 
num_workers: 1 # above 1 is experimental...
prune: 0 # no. of files to process, set to 0 to use all
overwrites: "off" # "on" or "off"
var_overwrites:
#  - "lat"
#  - "lon"
overwrite_source:
